image:
- Visual Studio 2017

environment:
  global:
    CARGO_INCREMENTAL: "0"
  matrix:
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: beta

cache:
  - 'C:\Users\appveyor\.cargo'

install:
  # Download ninja
  - mkdir C:\ninja-build
  - ps: (new-object net.webclient).DownloadFile('https://github.com/mesonbuild/cidata/raw/master/ninja.exe', 'C:\ninja-build\ninja.exe')
  # Set paths to dependencies (based on architecture)
  - set PYTHON_ROOT=C:\Python37-x64
  # Add neccessary paths to PATH variable
  - set PATH=%cd%;C:\ninja-build;%PYTHON_ROOT%;%PYTHON_ROOT%\Scripts;%PATH%
  # Install meson
  - pip install meson
  # Enable Visual Studio 2017
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  # Install rust
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  # Install cargo-wix
  - cargo install -f cargo-wix
  # Print versions
  - rustc --version --verbose
  - cargo --version
  - cargo wix --version
  - python --version
  - pip --version
  - meson --version

build_script:
  - cargo build --release
  - cargo wix --nocapture --name rebootinto --install-version "%APPVEYOR_BUILD_VERSION%"

test_script:
  - cargo test --release

artifacts:
  - path: target/release/rebootinto-tui.exe
    name: rebootinto-tui.exe
  - path: target/release/rebootinto-iui.exe
    name: rebootinto-iui.exe
  - path: target/wix/rebootinto-$(APPVEYOR_BUILD_VERSION)-x86_64.msi
    name: rebootinto-x86_64.msi
